#DELETE http://localhost:3000/user/49
POST http://localhost:3000/restore/user/49
Content-Type: application/json

{
  "firstName": "LongVip",
  "lastName": "Bui",
  "email": "test01@gmail.com",
  "password": "99"
}
